use crate::value::Value;

#[derive(Debug, Clone)]
pub enum Instruction {
    Const(Value),
    LoadVar(String),
    StoreVar(String),
    LoadLocal(usize),
    StoreLocal(usize),
    Add, Sub, Mul, Div, Mod, Pow,
    Neg,
    And, Or, Not,
    Eq, Ne, Gt, Lt, Ge, Le,
    Jump(isize),
    JumpIfFalse(isize),
    JumpIfTrue(isize),
    Call(usize),
    Return,
    MakeFunc(String, Vec<String>, usize),
    MakeClosure(usize, Vec<String>),
    MakeClass(String, Vec<(String, Vec<String>, Vec<Instruction>, Vec<String>)>),
    Instantiate(String),
    LoadMethod(String),
    MakeList(usize),
    MakeMap(usize),
    IndexGet,
    ListLen,
    AddToList,
    RemoveFromList,
    MapToList,
    Say,
    Ask(String),
    ReadFile(String),
    WriteFile,
    Raise,
    TryCatch(isize, isize),
    EndTry,
    TypeOf,
    Convert(String),
    Dup,
    Pop,
    Stop,
    Exit,
    Halt,
}
